version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20          # Node 20/22 are now in the standard images 🥳
    commands:
      - npm i -g pnpm
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm --filter web build:i18n
      - pnpm sst deploy --stage $STAGE --print-logs
cache:
  paths:
    - "/root/.pnpm-store/**"
