/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AirtableWebhookFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BuildQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageResizer": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "ImageResizerFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Web": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}